### ISSUE TITLE
Use azul.rs instead of C for composing graphics

### ISSUE THREAD

**Issue by danimesq** [ExPixel/Pyrite-old-#15]

**Comment by danimesq** [comment]
Is it implemented in https://github.com/ExPixel/Pyrite/commit/3ddf49eadb57c51efa05c9ea16b5fe77b6ac2a1a and https://github.com/ExPixel/Pyrite/commit/9b099688958821b36d4638b52cf83efa6cdd80d5 or yet relying in C?

**Comment by ExPixel** [comment]
Not yet implemented. Azul isn't really the direction I want to go in. I'll probably switch when a proper stable Rust GUI library shows up. Until then I'll just be using C/C++ wrappers.
